<!--
document.write("");
document.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" class=\"NoPrint\">");
document.write("  <tr>");
document.write("    <td width=\"10\" class=\"text_Menu\"><img src=\"/js/images/sp_menu01.gif\"  width=\"10\" height=\"30\" id=\"SCGMainImageMenu1\" /></td>");
document.write("    <td width=\"147\" class=\"text_Menu\" id=\"SCGMainMenu1\" style=\"cursor:hand;\" onClick=\"menu_click\(\' http://www.scg.co.th/th/01corporate_profile/\'\);\" OnMouseOver=\"NavMenu_display\(\'1\',this\)\" onMouseOut=\"timerID=setTimeout\(\'NavMenu_destroy\(\)\',600\);\"><div align=\"center\">&#3619;&#3641;&#3657;&#3592;&#3633;&#3585;&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637;</div></td>");
document.write("    <td width=\"10\"><img src=\"/js/images/sp_menu02.gif\" width=\"8\" height=\"30\" id=\"SCGMainImageMenu1R\"></td>");
document.write("");
document.write("    <td width=\"10\" class=\"text_Menu\"><img src=\"/js/images/sp_menu01.gif\"  width=\"10\" height=\"30\" id=\"SCGMainImageMenu2\" /></td>");
document.write("    <td width=\"147\" class=\"text_Menu\" id=\"SCGMainMenu2\" style=\"cursor:hand;\" onClick=\"menu_click\(\' http://www.scg.co.th/th/02business_overview/\'\);\" OnMouseOver=\"NavMenu_display\(\'2\',this\)\" onMouseOut=\"timerID=setTimeout\(\'NavMenu_destroy\(\)\',600\);\"><div align=\"center\">&#3608;&#3640;&#3619;&#3585;&#3636;&#3592;&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637;</div></td>");
document.write("    <td width=\"10\"><img src=\"/js/images/sp_menu02.gif\" width=\"8\" height=\"30\" id=\"SCGMainImageMenu2R\" /></td>");
document.write("");
document.write("<td width=\"10\" class=\"text_Menu\"><img src=\"/js/images/sp_menu01.gif\"  width=\"10\" height=\"30\" id=\"SCGMainImageMenu4\" /></td>");
document.write("<td width=\"147\" class=\"text_Menu\" id=\"SCGMainMenu4\" style=\"cursor:hand;\" onClick=\"menu_click\(\'/th/04investor_governance/\'\);\" OnMouseOver=\"NavMenu_display\(\'4\',this\)\" onMouseOut=\"timerID=setTimeout\(\'NavMenu_destroy\(\)\',600\);\"><div align=\"center\">&#3586;&#3657;&#3629;&#3617;&#3641;&#3621;&#3626;&#3635;&#3627;&#3619;&#3633;&#3610;&#3609;&#3633;&#3585;&#3621;&#3591;&#3607;&#3640;&#3609;</div></td>");
document.write("    <td width=\"10\"><img src=\"/js/images/sp_menu02.gif\"  width=\"8\" height=\"30\" id=\"SCGMainImageMenu4R\" /></td>");

document.write("");
document.write("<td width=\"10\" class=\"text_Menu\"><img src=\"/js/images/sp_menu01.gif\"  width=\"10\" height=\"30\" id=\"SCGMainImageMenu9\" /></td>");
document.write("<td width=\"126\" class=\"text_Menu\" id=\"SCGMainMenu9\" style=\"cursor:hand;\" onClick=\"menu_click\(\'http://scc-th.listedcompany.com/debenture_quotation.html\'\);\" OnMouseOver=\"NavMenu_display\(\'9\',this\)\" onMouseOut=\"timerID=setTimeout\(\'NavMenu_destroy\(\)\',600\);\"><div align=\"center\">&#3627;&#3640;&#3657;&#3609;&#3585;&#3641;&#3657;</div></td>");
document.write("    <td width=\"10\"><img src=\"/js/images/sp_menu02.gif\"  width=\"8\" height=\"30\" id=\"SCGMainImageMenu9R\" /></td>");

document.write("");
document.write("    <td width=\"10\" class=\"text_Menu\"><img src=\"/js/images/sp_menu01.gif\"  width=\"10\" height=\"30\" id=\"SCGMainImageMenu5\" /></td>");
document.write("    <td width=\"147\" class=\"text_Menu\" id=\"SCGMainMenu5\" style=\"cursor:hand;\" onClick=\"menu_click\(\' http://www.scg.co.th/th/05sustainability_development/\'\);\" OnMouseOver=\"NavMenu_display\(\'5\',this\)\" onMouseOut=\"timerID=setTimeout\(\'NavMenu_destroy\(\)\',600\);\"><div align=\"center\">&#3585;&#3634;&#3619;&#3614;&#3633;&#3602;&#3609;&#3634;&#3629;&#3618;&#3656;&#3634;&#3591;&#3618;&#3633;&#3656;&#3591;&#3618;&#3639;&#3609;</div></td>");
document.write("<td width=\"10\"><img src=\"/js/images/sp_menu02.gif\"  width=\"8\" height=\"30\" id=\"SCGMainImageMenu5R\" /></td>");
document.write("");
document.write("    <td width=\"10\" class=\"text_Menu\"><img src=\"/js/images/sp_menu01.gif\"  width=\"10\" height=\"30\" id=\"SCGMainImageMenu6\" /></td>");
document.write("    <td width=\"147\" class=\"text_Menu\" id=\"SCGMainMenu6\" style=\"cursor:hand;\" onClick=\"menu_click\(\' http://www.scg.co.th/th/06career_scg/\'\);\" OnMouseOver=\"NavMenu_display\(\'6\',this\)\" onMouseOut=\"timerID=setTimeout\(\'NavMenu_destroy\(\)\',600\);\"><div align=\"center\">&#3619;&#3656;&#3623;&#3617;&#3591;&#3634;&#3609;&#3585;&#3633;&#3610;&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637;</div></td>");
document.write("<td width=\"10\"><img src=\"/js/images/sp_menu02.gif\"  width=\"8\" height=\"30\" id=\"SCGMainImageMenu6R\" /></td>");
document.write("");
document.write("    <td width=\"10\" class=\"text_Menu\"><img src=\"/js/images/sp_menu01.gif\"  width=\"10\" height=\"30\" id=\"SCGMainImageMenu8\" /></td>");
document.write("    <td width=\"176\" class=\"text_Menu\" id=\"SCGMainMenu8\" style=\"cursor:hand;\" onClick=\"menu_click\(\' http://www.scg.co.th/th/08news_release/01_news.html\'\);\" OnMouseOver=\"NavMenu_display\(\'8\',this\)\" onMouseOut=\"timerID=setTimeout\(\'NavMenu_destroy\(\)\',600\);\"><div align=\"center\">&#3586;&#3656;&#3634;&#3623;&#3649;&#3621;&#3632;&#3588;&#3623;&#3634;&#3617;&#3648;&#3588;&#3621;&#3639;&#3656;&#3629;&#3609;&#3652;&#3627;&#3623;</div></td>");
document.write("<td width=\"8\"><img src=\"/js/images/sp_menu02.gif\"  width=\"8\" height=\"30\" id=\"SCGMainImageMenu8R\" /></td>");
document.write("");
document.write("  </tr>");
document.write("</table>");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu1\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("  <tr>");
document.write("    <td height=\"5\" bgcolor=\"#C9C9C2\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon11\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon11\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr onClick=\"menu_click\(\' http://www.scg.co.th/th/01corporate_profile/\'\);\" >");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon11\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/01_business_philosophy.html\"> &#3629;&#3640;&#3604;&#3617;&#3585;&#3634;&#3619;&#3603;&#3660;&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon12\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon12\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon12\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/02_scg_vision.html\">&#3623;&#3636;&#3626;&#3633;&#3618;&#3607;&#3633;&#3624;&#3609;&#3660;&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon13\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon13\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon13\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/03_milstone.html\">&#3611;&#3619;&#3632;&#3623;&#3633;&#3605;&#3636;&#3588;&#3623;&#3634;&#3617;&#3648;&#3611;&#3655;&#3609;&#3617;&#3634;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon14\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon14\'\)\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu14\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon14\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/04_management_team.html\">&#3588;&#3603;&#3632;&#3592;&#3633;&#3604;&#3585;&#3634;&#3619;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon142\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon142\'\)\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu142\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon142\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/05_board_of_director.html\">&#3588;&#3603;&#3632;&#3585;&#3619;&#3619;&#3617;&#3585;&#3634;&#3619;&#3610;&#3619;&#3636;&#3625;&#3633;&#3607;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>  ");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon15\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon15\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon15\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/05_business_structure.html\">&#3650;&#3588;&#3619;&#3591;&#3626;&#3619;&#3657;&#3634;&#3591;&#3629;&#3591;&#3588;&#3660;&#3585;&#3619;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("        <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon16\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon16\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon16\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/06_message_from_director.html\">&#3626;&#3634;&#3619;&#3592;&#3634;&#3585;&#3588;&#3603;&#3632;&#3585;&#3619;&#3619;&#3617;&#3585;&#3634;&#3619; </a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon17\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon17\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon17\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/07_corporate_governance.html\">&#3610;&#3619;&#3619;&#3625;&#3633;&#3607;&#3616;&#3636;&#3610;&#3634;&#3621;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  ");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon18\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon18\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon18\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/08_award_standards.html\">&#3619;&#3634;&#3591;&#3623;&#3633;&#3621;&#3649;&#3627;&#3656;&#3591;&#3588;&#3640;&#3603;&#3616;&#3634;&#3614;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon19\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon19\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon19\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/01corporate_profile/09_innovation_rd_guideline.html\">&#3629;&#3591;&#3588;&#3660;&#3585;&#3619;&#3649;&#3627;&#3656;&#3591;&#3609;&#3623;&#3633;&#3605;&#3585;&#3619;&#3619;&#3617;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("</table>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu2\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("  <tr>");
document.write("    <td height=\"5\" bgcolor=\"#C9C9C2\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon21\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon21\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon21\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"http://www.scg.co.th/th/02business_overview/01_scg_chemicals_business.html \" class=\"SimpleModalTh\" title=\"&nbsp;\">&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637; &#3648;&#3588;&#3617;&#3636;&#3588;&#3629;&#3621;&#3626;&#3660;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon22\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon22\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon22\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"http://www.scg.co.th/th/02business_overview/02_scg_paper_business.html\" class=\"SimpleModalTh\" title=\"&nbsp;\">&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637; &#3648;&#3611;&#3648;&#3611;&#3629;&#3619;&#3660;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon23\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon23\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon23\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"http://www.scg.co.th/th/02business_overview/03_scg_cement_business.html\" class=\"SimpleModalTh\" title=\"&nbsp;\">&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637; &#3595;&#3636;&#3648;&#3617;&#3609;&#3605;&#3660;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon24\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon24\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon24\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"http://www.scg.co.th/th/02business_overview/04_scg_building_materials_business.html\" class=\"SimpleModalTh\" title=\"&nbsp;\">&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637; &#3612;&#3621;&#3636;&#3605;&#3616;&#3633;&#3603;&#3601;&#3660;&#3585;&#3656;&#3629;&#3626;&#3619;&#3657;&#3634;&#3591;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon25\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon25\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon25\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"http://www.scg.co.th/th/02business_overview/05_scg_distribution_business.html\" class=\"SimpleModalTh\" title=\"&nbsp;\">&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637; &#3604;&#3637;&#3626;&#3607;&#3619;&#3636;&#3610;&#3636;&#3623;&#3594;&#3633;&#3656;&#3609;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onmouseover=\"NavMenu_mover\(this,\'SMIcon26\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon26\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\" /></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon26\" /></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\" /></td>");
document.write("        <td><a href=\"http://www.scg.co.th/th/02business_overview/other_business.html\" class=\"SimpleModalTh\" title=\"&nbsp;\">&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637; &#3585;&#3634;&#3619;&#3621;&#3591;&#3607;&#3640;&#3609;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("        <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("</table>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu3\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("  <tr>");
document.write("    <td height=\"5\" bgcolor=\"#C9C9C2\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon31\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon31\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon31\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3648;&#3588;&#3617;&#3637;&#3616;&#3633;&#3603;&#3601;&#3660;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon32\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon32\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon32\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3585;&#3619;&#3632;&#3604;&#3634;&#3625;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon33\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon33\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon33\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3611;&#3641;&#3609;&#3595;&#3637;&#3648;&#3617;&#3609;&#3605;&#3660; / &#3588;&#3629;&#3609;&#3585;&#3619;&#3637;&#3605;&#3612;&#3626;&#3617;&#3648;&#3626;&#3619;&#3655;&#3592;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon35\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon35\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon35\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\"#\">&#3612;&#3621;&#3636;&#3605;&#3616;&#3633;&#3603;&#3601;&#3660;&#3585;&#3656;&#3629;&#3626;&#3619;&#3657;&#3634;&#3591;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon36\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon36\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon36\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\"#\">&#3592;&#3633;&#3604;&#3592;&#3635;&#3627;&#3609;&#3656;&#3634;&#3618;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("</table>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu4\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("    <tr>");
document.write("      <td bgcolor=\"#C9C9C2\" height=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon40\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon40\'\);\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon40\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a href=\"http://scc-th.listedcompany.com/misc/ir_kits/SCC_investorKits-TH.zip\" target=\"_blank\">Download IR Kits</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon41\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon41\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon41\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/financial_overview.html\">&#3586;&#3657;&#3629;&#3617;&#3641;&#3621;&#3607;&#3634;&#3591;&#3585;&#3634;&#3619;&#3648;&#3591;&#3636;&#3609;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon42\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon42\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon42\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/ar.html\">&#3619;&#3634;&#3618;&#3591;&#3634;&#3609;&#3611;&#3619;&#3632;&#3592;&#3635;&#3611;&#3637;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon43\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon43\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon43\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/stock_price.html\">&#3586;&#3657;&#3629;&#3617;&#3641;&#3621;&#3619;&#3634;&#3588;&#3634;&#3627;&#3621;&#3633;&#3585;&#3607;&#3619;&#3633;&#3614;&#3618;&#3660;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon44\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon44\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon44\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/cg.html\">&#3585;&#3634;&#3619;&#3585;&#3635;&#3585;&#3633;&#3610;&#3604;&#3641;&#3649;&#3621;&#3585;&#3636;&#3592;&#3585;&#3634;&#3619;&#3607;&#3637;&#3656;&#3604;&#3637;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon45\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon45\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon45\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/newsroom_set.html\">&#3627;&#3657;&#3629;&#3591;&#3586;&#3656;&#3634;&#3623;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" alt=\"\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon46\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon46\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon46\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/factsheet.html\">&#3586;&#3657;&#3629;&#3617;&#3641;&#3621;&#3626;&#3635;&#3627;&#3619;&#3633;&#3610;&#3612;&#3641;&#3657;&#3606;&#3639;&#3629;&#3627;&#3640;&#3657;&#3609;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon47\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon47\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon47\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/debenture_quotation.html\">&#3627;&#3640;&#3657;&#3609;&#3585;&#3641;&#3657;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon48\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon48\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon48\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/analyst_contact.html\">&#3586;&#3657;&#3629;&#3617;&#3641;&#3621;&#3609;&#3633;&#3585;&#3623;&#3636;&#3648;&#3588;&#3619;&#3634;&#3632;&#3627;&#3660;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon49\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon49\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon49\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/slides.html\">&#3648;&#3629;&#3585;&#3626;&#3634;&#3619;&#3609;&#3635;&#3648;&#3626;&#3609;&#3629; \(English Only\)</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon410\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon410\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon410\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/webcast.html\">WebCast</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon411\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon411\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon411\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/supplementary.html\">Supplementary Info.</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td><table width=\"250\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"text_Sub_Menu_Top\"");
document.write("                    onmouseout=\"NavMenu_mout\(this,\'SMIcon412\'\)\" onmouseover=\"NavMenu_mover\(this,\'SMIcon412\'\);\"");
document.write("                    style=\"cursor: pointer;\">");
document.write("          ");
document.write("            <tr>");
document.write("              <td width=\"12\"><img width=\"12\" height=\"25\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td width=\"6\"><img width=\"6\" height=\"5\" id=\"SMIcon412\" src=\"/js/images/arrow01.gif\"> </td>");
document.write("              <td width=\"5\"><img width=\"5\" height=\"5\" src=\"/js/images/spacer.gif\"> </td>");
document.write("              <td><a target=\"_blank\" href=\"http://www.scg.co.th//th/ir/email_alerts.html\">&#3626;&#3629;&#3610;&#3606;&#3634;&#3617;&#3586;&#3657;&#3629;&#3617;&#3641;&#3621;&#3609;&#3633;&#3585;&#3621;&#3591;&#3607;&#3640;&#3609;</a> </td>");
document.write("            </tr>");
document.write("          ");
document.write("      </table></td>");
document.write("    </tr>");
document.write("    <tr>");
document.write("      <td bgcolor=\"#FFFFFF\"><img width=\"10\" height=\"1\" src=\"/js/images/spacer.gif\"> </td>");
document.write("    </tr>");
document.write("  ");
document.write("</table>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu5\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("  <tr>");
document.write("    <td height=\"5\" bgcolor=\"#C9C9C2\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td align=\"left\"><div align=\"left\">");
document.write("      <table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon51\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon51\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon51\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"http://www.scg.co.th/th/05sustainability_development/08_scg-eco-value.html\">SCG Eco Value </a> </td>");
document.write("        </tr>");
document.write("      </table>");
document.write("    </div>");
document.write("      </td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon51\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon51\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon51\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\" http://www.scg.co.th/th/05sustainability_development/01_sustainable_management.html\">&#3585;&#3634;&#3619;&#3610;&#3619;&#3636;&#3627;&#3634;&#3619;&#3592;&#3633;&#3604;&#3585;&#3634;&#3619;&#3648;&#3614;&#3639;&#3656;&#3629;&#3588;&#3623;&#3634;&#3617;&#3618;&#3633;&#3656;&#3591;&#3618;&#3639;&#3609; ");
document.write("</a> </td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon52\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon52\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon52\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/05sustainability_development/02_environmental_performance_indicators.html\">&#3604;&#3633;&#3594;&#3609;&#3637;&#3594;&#3637;&#3657;&#3623;&#3633;&#3604;&#3604;&#3657;&#3634;&#3609;&#3626;&#3636;&#3656;&#3591;&#3649;&#3623;&#3604;&#3621;&#3657;&#3629;&#3617;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon53\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon53\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon53\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/05sustainability_development/03_sustainability_report.html\">&#3619;&#3634;&#3618;&#3591;&#3634;&#3609;&#3585;&#3634;&#3619;&#3614;&#3633;&#3602;&#3609;&#3634;&#3629;&#3618;&#3656;&#3634;&#3591;&#3618;&#3633;&#3656;&#3591;&#3618;&#3639;&#3609;");
document.write("</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon54\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon54\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon54\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/05sustainability_development/04_safety_environmental.html\">&#3585;&#3634;&#3619;&#3592;&#3633;&#3604;&#3585;&#3634;&#3619;&#3588;&#3623;&#3634;&#3617;&#3611;&#3621;&#3629;&#3604;&#3616;&#3633;&#3618; / &#3626;&#3636;&#3656;&#3591;&#3649;&#3623;&#3604;&#3621;&#3657;&#3629;&#3617;</a> </td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon55\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon55\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon55\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/05sustainability_development/05_social_community.html\">&#3585;&#3634;&#3619;&#3614;&#3633;&#3602;&#3609;&#3634;&#3626;&#3633;&#3591;&#3588;&#3617; / &#3594;&#3640;&#3617;&#3594;&#3609;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
/*document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon56\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon56\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon56\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\"http://www.scgfoundation.org\" target=\"_blank\">&#3617;&#3641;&#3621;&#3609;&#3636;&#3608;&#3636;&#3595;&#3636;&#3648;&#3617;&#3609;&#3605;&#3660;&#3652;&#3607;&#3618;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("        <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon57\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon57\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon57\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/05sustainability_development/07_survey_corporate_image.html\">&#3612;&#3621;&#3585;&#3634;&#3619;&#3623;&#3636;&#3592;&#3633;&#3618;&#3616;&#3634;&#3614;&#3621;&#3633;&#3585;&#3625;&#3603;&#3660;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");*/
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("</table>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu6\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("  <tr>");
document.write("    <td height=\"5\" bgcolor=\"#C9C9C2\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon651\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon651\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon651\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/06career_scg/03_internship_trainee_blog.html\">&#3585;&#3634;&#3619;&#3614;&#3633;&#3602;&#3609;&#3634;&#3614;&#3609;&#3633;&#3585;&#3591;&#3634;&#3609;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>  ");
document.write("  <tr>");
document.write("     <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onmouseover=\"NavMenu_mover\(this,\'SMIcon65\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon65\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\" /></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon65\" /></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\" /></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/06career_scg/02_career_camp_information.html\">SCG Career Camp</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("     <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onmouseover=\"NavMenu_mover\(this,\'SMIcon65\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon65\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\" /></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon65\" /></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\" /></td>");
document.write("        <td><a href=\"http://e-application.scg.co.th\">&#3626;&#3617;&#3633;&#3588;&#3619;&#3591;&#3634;&#3609;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>  ");
document.write("</table>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu7\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("  <tr>");
document.write("    <td height=\"5\" bgcolor=\"#C9C9C2\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon71\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon71\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon71\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3626;&#3629;&#3610;&#3606;&#3634;&#3617;&#3607;&#3633;&#3656;&#3623;&#3652;&#3611; / &#3649;&#3609;&#3632;&#3609;&#3635;&#3605;&#3636;&#3594;&#3617;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon72\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon72\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon72\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3609;&#3633;&#3585;&#3621;&#3591;&#3607;&#3640;&#3609;&#3626;&#3633;&#3617;&#3614;&#3633;&#3609;&#3608;&#3660;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon73\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon73\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon73\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3626;&#3634;&#3618;&#3604;&#3656;&#3623;&#3609;&#3588;&#3609;&#3619;&#3633;&#3585;&#3610;&#3657;&#3634;&#3609;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon74\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon74\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon74\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3626;&#3617;&#3633;&#3588;&#3619;&#3591;&#3634;&#3609;&#3585;&#3633;&#3610;&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon75\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon75\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon75\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\"#\">&#3626;&#3606;&#3634;&#3609;&#3607;&#3637;&#3656;&#3605;&#3636;&#3604;&#3605;&#3656;&#3629;</a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon76\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon76\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon76\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\"#\">&#3586;&#3657;&#3629;&#3648;&#3626;&#3609;&#3629;&#3649;&#3609;&#3632;&#3648;&#3623;&#3655;&#3610;&#3652;&#3595;&#3605;&#3660;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("</table>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0EA\" class=\"text_Sub_Menu_Top\" id=\"SCGMenu8\" style=\"z-index: 1000;display:none;position:absolute\">");
document.write("  <tr>");
document.write("    <td height=\"5\" bgcolor=\"#C9C9C2\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("  </tr>");
document.write("  <tr>");

document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon81\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon81\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon81\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td><a href=\" http://www.scg.co.th/th/08news_release/01_news_archive.html\">&#3586;&#3656;&#3634;&#3623;&#3618;&#3657;&#3629;&#3609;&#3627;&#3621;&#3633;&#3591; </a></td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon83\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon83\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon83\"></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("          <td>&#3626;&#3639;&#3656;&#3629;&#3650;&#3590;&#3625;&#3603;&#3634;</td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon84\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon84\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"24\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/bullet03.gif\" width=\"6\" height=\"5\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/08news_release/02_tvc.html\">&#3616;&#3634;&#3614;&#3618;&#3609;&#3605;&#3619;&#3660;&#3650;&#3590;&#3625;&#3603;&#3634;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("<tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon85\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon85\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"24\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/bullet03.gif\" width=\"6\" height=\"5\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/08news_release/02_printing.html\">&#3626;&#3639;&#3656;&#3629;&#3650;&#3590;&#3625;&#3603;&#3634;&#3626;&#3636;&#3656;&#3591;&#3614;&#3636;&#3617;&#3614;&#3660;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("<tr>");
document.write("          <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onmouseover=\"NavMenu_mover\(this,\'SMIcon85\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon85\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("        <tr>");
document.write("          <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"24\" height=\"25\" /></td>");
document.write("          <td width=\"6\"><img src=\"/js/images/bullet03.gif\" width=\"6\" height=\"5\" /></td>");
document.write("          <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\" /></td>");
document.write("          <td><a href=\" http://www.scg.co.th/th/08news_release/04_photo_library.html\">&#3588;&#3621;&#3633;&#3591;&#3619;&#3641;&#3611;&#3616;&#3634;&#3614; </a></td>");
document.write("        </tr>");
document.write("      </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><table width=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" onMouseOver=\"NavMenu_mover\(this,\'SMIcon86\'\);\"  onmouseout=\"NavMenu_mout\(this,\'SMIcon86\'\)\" class=\"text_Sub_Menu_Top\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"/js/images/spacer.gif\" width=\"12\" height=\"25\"></td>");
document.write("        <td width=\"6\"><img src=\"/js/images/arrow01.gif\"  width=\"6\" height=\"5\" id=\"SMIcon86\"></td>");
document.write("        <td width=\"5\"><img src=\"/js/images/spacer.gif\" width=\"5\" height=\"5\"></td>");
document.write("        <td><a href=\" http://www.scg.co.th/th/08news_release/03_publication.html\">&#3626;&#3636;&#3656;&#3591;&#3614;&#3636;&#3617;&#3614;&#3660;&#3629;&#3639;&#3656;&#3609;&#3654;&#3586;&#3629;&#3591;&#3648;&#3629;&#3626;&#3595;&#3637;&#3592;&#3637;</a></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td bgcolor=\"#FFFFFF\"><img src=\"/js/images/spacer.gif\" width=\"10\" height=\"1\"></td>");
document.write("  </tr>");
document.write("</table>");

var Menu = false;
var leftPos = false;
var topPos = false;
var timerID = false;
var objTdMenu = false;
var strCurrentMenuId	=	"";



function NavMenu_mover(theObj,objImageId)
{
	theObj.style.cursor = 'hand';
	if (document.getElementById(objImageId)) { document.getElementById(objImageId).src = "/js/images/arrow01_a.gif"; }
	clearTimeout(timerID);
	theObj.className = "text_Sub_Menu_Top_Over";
}

function NavMenu_mout(theObj,objImageId)
{
	theObj.style.cursor = 'pointer';
	if (document.getElementById(objImageId)) { document.getElementById(objImageId).src = "/js/images/arrow01.gif"; }		
	timerID = setTimeout("NavMenu_destroy()",600);
	theObj.className = "text_Sub_Menu_Top";
}





function NavSubMenu_left_mover(theObj,objImageId)
{
	NavMenu_destroy();
	theObj.style.cursor = 'hand';
	if (document.getElementById(objImageId)) { document.getElementById(objImageId).src = "/js/images/arrow01_a.gif"; }
	theObj.className = "text_Sub_Menu_Left_Over";
}

function NavSubMenu_left_mout(theObj,objImageId)
{
	theObj.style.cursor = 'pointer';
	if (document.getElementById(objImageId)) { document.getElementById(objImageId).src = "/js/images/arrow01.gif"; }	
	theObj.className = "text_Sub_Menu_Left";
}





function NavMenu_display(setMenu,obj)
{
	NavMenu_destroy();
	clearTimeout(timerID);

	Menu = document.getElementById("SCGMenu"+setMenu);
	leftPos = findPosX(obj);
	topPos = obj.height;

	if (setMenu == "1") {
		leftPos	-=	9;
	}
	else if (setMenu == "8") {
		leftPos	-=	96;
	}
	else {
		leftPos	-=	10;
	}

	Menu.style.left = leftPos+'px';
	//Menu.style.top = topPos+'px';
	Menu.style.display = '';

	objTdMenu = obj;
	strCurrentMenuId = setMenu;

	objTdMenu.className = "text_Menu_Over";
	if (document.getElementById("SCGMainImageMenu"+strCurrentMenuId)) {
		document.getElementById("SCGMainImageMenu"+strCurrentMenuId).src = "/js/images/sp_menu01_a.gif";	
		document.getElementById("SCGMainImageMenu"+strCurrentMenuId+"R").src = "/js/images/sp_menu02_a.gif";	
	}
}

function NavMenu_destroy()
{
	if(Menu) Menu.style.display = 'none';

	objTdMenu.className = "text_Menu";
	if (document.getElementById("SCGMainImageMenu"+strCurrentMenuId)) {
		document.getElementById("SCGMainImageMenu"+strCurrentMenuId).src = "/js/images/sp_menu01.gif";	
		document.getElementById("SCGMainImageMenu"+strCurrentMenuId+"R").src = "/js/images/sp_menu02.gif";
	}
}




function menu_click(url)
{
	location.href=url;
}

function menu_click_new_window(url)
{
	window.open(url,"SCGPopup1","width=940,height=680,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes");		
}






function findPosX(obj)
{
	var curleft = 0;
	if (obj.offsetParent)
	{
		while (obj.offsetParent)
		{
			curleft += obj.offsetLeft
			obj = obj.offsetParent;
		}
	}
	else if (obj.x)
		curleft += obj.x;
	return curleft;
}

function findPosY(obj)
{
	var curtop = 0;
	if (obj.offsetParent)
	{
		while (obj.offsetParent)
		{
			curtop += obj.offsetTop
			obj = obj.offsetParent;
		}
	}
	else if (obj.y)
		curtop += obj.y;
	return curtop;
}
-->